### ISSUE TITLE
монорепозитории

### ISSUE THREAD

**Issue by AlexR0v** [Atlantis-Academy/react-learn#10]
прочитать и разобраться в особенностях монорепозитория, вот хорошие статьи, в них рассматриваются основные команды lerna, что такое воркспейсы и пр. Прочитав, ты поймешь, почему сейчас твоя структура не похожа на монорепозиторий и, надеюсь, поймешь что нужно сделать.

https://habr.com/ru/company/yandex/blog/469021/

https://habr.com/ru/post/448766/

 - deadline - 10.09 23:59 МСК - проект должен быть оформлен в виде монорепозитория (пакеты, версии, все дела)

**Comment by AlexR0v** [comment]
текст @TorinAsakura 

Версионирование
Что это такое?
Заранее определенная методика назначения версий для разрабатываемых пакетов, модулей и т.п. Почти во всех случаях используется semver. Обязательно к прочтению: https://semver.org/lang/ru/

Для чего?
В-нулевых, глядя на версию, можно с легкостью определить характер изменений. Во-первых, чтобы участники могли получать то состояние системы, которое требуется. Это удобно как для тестирования, так и для разворачивания систем. Во-вторых, это позволяет контролировать законченность реализуемых фич и принимать решение о публикации наработок. В-третьих, версии формируют своеобразный таймлайн, поверх которого собирается changelog.

Как пользоваться?
Новые версии создаются с помощью lerna version. См. https://github.com/lerna/lerna/tree/master/commands/version Т.к. пушить в дев напрямую нельзя, то релизы заводятся через отдельную ветку с PR. Ветку называем chore/release. Льем на GH. После этого запускаем lerna version --conventional-commits. conventional-commits нужен для того, чтобы правильно собрать CHANGELOG.md. После выполнения команды льем коммиты в тукущую ветку и заводим PR. Релиз готов.

С какой версии начинать новые пакеты? (см. монорепо)
Новый пакет всегда начинается с 0.0.0. Не 0.0.1, не 1.0.0. Только 0.0.0. lerna version сам потом назначит нужную версию, если возникнет такая необходимость.

**Comment by AlexR0v** [comment]
1. Выставляем все версии созданных пакетов 0.0.0
2. Проверяем что мы не в ветке dev
3. запускаем в консоли команду: lerna version --conventional-commits
4. После выполнения команды льем коммиты в тукущую ветку и заводим PR. Релиз готов.

**Comment by TorinAsakura** [comment]
@AlexR0v это зачем тут? Вам интернета мало?

**Comment by AlexR0v** [comment]
Лучшего пояснения по версионированию я не нашел. И сам долго не мог разобраться пока не прочел это.
