### ISSUE TITLE
backgroundImage for Box component

### ISSUE THREAD

**Issue by gochicus** [Atlantis-Academy/react-learn#11]
Компонент Box - https://github.com/Atlantis-Lab/uikit/blob/master/packages/layout/src/Box.ts по умолчанию не импортирует background. 

Думал решить проблему инлайн стилизацией:
 <Box
        style={{backgroundImage:"url('./../../../ui/img/src/wow.jpg')"}}
        height={455}
        width={288}
      >
Перепробовал несколько вариантов написания, использовать require, но все равно изображение не находится. В чем проблема?

**Comment by AlexR0v** [comment]
@gochicus ,  Нужен background? Создай компонент Background и надели теми свойствами, которые тебе нужны.

**Comment by TorinAsakura** [comment]
@gochicus вообще не понимаю, а почему Box должен что-то импортировать? Box это просто флекс блок который можно декорировать
@AlexR0v полагаю тебе надо ещё раз провести лекцию

**Comment by AlexR0v** [comment]
@gochicus , и проблема в путях - './../../../ui/img/src/wow.jpg - по сути ты в начале говоришь - зайди в текущую папку (./), поднимись на уровень выше (../), уже все запутал - так в текущей директории или выше, где искать картинку то?

@TorinAsakura , ок.

**Comment by gochicus** [comment]
<img  src={require('./../../../ui/img/src/wc.jpg')}  alt='Warcraft'  /> Я изначально не сообразил, по пути с картинкой пошел, так вот вот этот путь абсолютно нормально открывает картинку. 
**"url('./../../../ui/img/src/wow.jpg')"** - Здесь происходит выход из папки src,Herj, components,  он оказывается в в папке site, тут указано искать в той же папке (site), дальше идет ui  и так далее. Такая логика

**Comment by AlexR0v** [comment]
предположим так и есть, но кто мешает сюда backgroundImage:"url('./../../../ui/img/src/wow.jpg')" запихнуть require? если с ним все работает. Посмотри как ты шрифты доставал, тут то же самое - url('${require(`./../../../ui/img/src/wow.jpg`)}')

**Comment by TorinAsakura** [comment]
@gochicus такое дерьмо нужно постоянно держать в голове, а зачем? Наша задача писать гибкий и масштабируемый код, с которым будет легко и понятно работать, а это грабли
