### ISSUE TITLE
ThumbSlider

### ISSUE THREAD

**Issue by gochicus** [Atlantis-Academy/react-learn#12]
Как стилизовать ползунок range? Возможно, я просто пишу его неправильно, но у меня пока нет больше идей. 
export const StyledInput = styled.input({
    appearance:'none',
    backgroundColor:'#006D75',
    borderRadius:'3px',
    height:'8px',
        WebkitSliderThumb:{
        appearance:'none',
        backgroundColor: '#13C2C2',
        borderRadius: '3px',
        height:'16px',
        width:'46px'
    }
}
)

**Comment by AlexR0v** [comment]
Мне Андрей как то давал эту ссылку, очень часто выручала, держи
https://google.gik-team.com/?q=%D0%BA%D0%B0%D0%BA+%D1%81%D1%82%D0%B8%D0%BB%D0%B8%D0%B7%D0%BE%D0%B2%D0%B0%D1%82%D1%8C+%D0%BF%D0%BE%D0%BB%D0%B7%D1%83%D0%BD%D0%BE%D0%BA+range%26

**Comment by gochicus** [comment]
Ок, тогда как сформулировать запрос? Я перерыл кучу страниц, где хорошо объясняется как сделать это на css.

**Comment by AlexR0v** [comment]
чет, я не пойму, если там все хорошо объясняется как это сделать, тогда в чем вопрос-то? в emotion все очень похоже на css они и говорят у себя об этом документации. Прочти второй параграф - https://emotion.sh/docs/styled

**Comment by gochicus** [comment]
Ползунок делается через псевдокласс, и все упирается именно в него.  Я вот не нашел ничего именно про псевдоклассы в emotion и сделал как привел выше. Вот еще один вариант(тоже не рабочий, но хотелось бы услышать - я хоть в правильном направлении иду?):
const thumb = ({thumb})=> (
  <input type='range' className={thumb} />)


export const StyledInput = styled(thumb)`
 .slider {
    -webkit-appearance: none;  
    appearance: none;
    width: 100%; 
    height: 25px; /
    background: 
    outline: none; 
    opacity: 0.7; 
    -webkit-transition: .2s; 
    transition: opacity .2s;
    
 .slider::-webkit-slider-thumb {
    -webkit-appearance: none; 
    appearance: none;
    width: 25px; 
    height: 25px; 
    background: #4CAF50; 
    cursor: pointer; 
}
`
