### ISSUE TITLE
Пример package.json

### ISSUE THREAD

**Issue by gochicus** [Atlantis-Academy/react-learn#13]
Интересуют две эти строки из примера(https://github.com/Atlantis-Academy/react-learn-landing/blob/dev/package.json):
 "landing:dev": "yarn workspace @landing/app dev",
 "lerna:link": "lerna link"

Я так понял верхняя задает рабочую область для проекта, лерна будет запускаться оттуда. Так ли это?  Затем,  что означает dev после landing и dev после @landing/app?

**Comment by AlexR0v** [comment]
не обращай на них внимания, это мне нужно было когда я запускал проект в docker.

**Comment by TorinAsakura** [comment]
@AlexR0v @Alex_R0v он задал вопрос и вопрос нормальный, это относится к делу.

**Comment by AlexR0v** [comment]
@gochicus , 
1. первый скрипт означает  - выполнить скрипт dev из package.json, который находится в пакете @landing/app.
2. второй скрипт означает выполнить команду lerna link.
Таким образом,  
1. в терминале я в вожу команду - yarn landing:dev - выполняется скрипт в пакете @landing/app, который звучит как dev, что делает он, нужно смотреть уже в самом пакете - он выполняет команду next dev.
2. я ввожу в терминале команду yarn lerna:link и выполняется команда lerna link

Зачем такие сложности? для докера он понимает только скрипты из корневого package.json.

Ломано, конечно, но как будем внедрять докер, так сразу станет понятней. Его внедрять предлагаю после внедрения next.js, т.к. у меня со стандартным девсервором ничего не получалось.
