### ISSUE TITLE
сверстать хедер проекта

### ISSUE THREAD

**Issue by AlexR0v** [Atlantis-Academy/react-learn#3]
для стилей использовать emotion, задействовать theme - https://emotion.sh/docs/theming - посмотри как в документации используется. Создать ветку dev от нее создать другую ветку, все изменения вести в ней, напрямую пушить в dev запрещено - только через PR. Коммиты все по conventional commits - https://www.conventionalcommits.org/en/v1.0.0/.
все что касается стилизации должно быть в папке ui.

**Comment by AlexR0v** [comment]
https://www.github.com/Atlantis-Academy/react-learn-landing/tree/feature%2Fhero-section/landing%2Fui%2Ftheme%2Fsrc 

Подключение шрифтов и глобальных стилей, посмотри как пример

**Comment by AlexR0v** [comment]
Styled-system - https://styled-system.com/

Row, column, layout, text- стилизуются с помощью этого инструмента. Дока небольшая и очень понятная.

**Comment by AlexR0v** [comment]
Svg преобразовываем через react-svgr, по ссылке онлайн конструктор, там же есть ссылка на документацию. Используем как обычный реакт компонент 

https://react-svgr.com/playground/

**Comment by TorinAsakura** [comment]
> Styled-system - https://styled-system.com/
> 
> Row, column, layout, text- стилизуются с помощью этого инструмента. Дока небольшая и очень понятная.

https://www.npmjs.com/package/@atlantis-lab/layout

**Comment by TorinAsakura** [comment]
> Svg преобразовываем через react-svgr, по ссылке онлайн конструктор, там же есть ссылка на документацию. Используем как обычный реакт компонент
> 
> https://react-svgr.com/playground/

https://github.com/Atlantis-Lab/uikit/tree/master/packages/icons
