### ISSUE TITLE
текстовые компоненты 

### ISSUE THREAD

**Issue by AlexR0v** [Atlantis-Academy/react-learn#9]
Для текста использовать react-intl и все мессаджи выности в отдельный messages.ts

пример message.ts - https://github.com/Atlantis-Academy/react-learn-landing/blob/chore/release/landing/sections/hero/src/Messages.tsx

пример использования в коде - https://github.com/Atlantis-Academy/react-learn-landing/blob/chore/release/landing/sections/hero/src/Title.tsx

пример подключения к проекту - https://github.com/Atlantis-Academy/react-learn-landing/blob/chore/release/landing/app/src/index.tsx

документация - https://formatjs.io/docs/getting-started/installation

**Comment by TorinAsakura** [comment]
@AlexR0v status?
